# Dropdown-Optionen für Marsh-Dateneingabe
# Alle möglichen Optionen werden hier definiert. Die zur Bearbeitung freigegbenen Listen werden in edit_selection.py gespeichert.
#region ***insurer_opt***
insurer_opt = ['ACQUINEX GMBH',
'AIG Europe S.A.',
'AIG Europe SA',
'AIG Europe SA (Denmark Branch)',
'Aioi Nissay Dowa Insurance',
'Allcura Versicherungs-AG',
'Allianz Elementar Vers.-AG',
'ALLIANZ ESA GMBH',
'Allianz Global Corporate &',
'Allianz Lebensversicherungs-AG',
'Allianz Versicherung AG',
'Allianz Versicherung AG,',
'Allianz Versicherungs-',
'Allianz Versicherungs-AG',
'Allied World Assurance Company',
'ALTA SIGNA EUROPE BV',
'Alte Leipziger Vers. AG',
'ALTE LEIPZIGER Versicherung',
'AMBRIDGE EUROPE GMBH & CO. KG',
'American Intern.Group UK Ltd.',
'AMERICAN INTERNATIONAL UNDER-',
'ANV SPECIALTY EUROPE S.L.',
'APPLIED FINANCIAL LINESINT.SAS',
'ARAG SE',
'ASSEKURANZ-KONTOR MONTAN GMBH',
'ASSEKURANZ-UNION',
'Assicurazioni Generali S.p.A',
'ASSPRO MANAGERLINE AG',
'Assuranceforeningen Gard',
'AT NORDDEUT. ASSEKURADEUR GMBH',
'Atradius Kreditversicherung',
'Auxilia Allg. Rechtsschutz-',
'AWP Health & Life SA',
'AXA Krankenversicherung AG',
'AXA Versicherung AG',
'Axis Specialty Europe SE',
'BA die Bayerische Allgemeine',
'Badischer Gemeinde-Ver-',
'Baloise Sachversicherung AG',
'BARKMANN*FRIEDRICH',
'Barmenia Krankenversicherung',
'Basler Versicherungs-',
'Bayer. Versicherungsverband',
'Bayerische Landesbrandver-',
'BDJ ASSEKURADEUR GMBH',
'Beazley Insurance dac',
'BEAZLEY INSURANCE DAC MüNCHEN',
'Berkshire Hathaway European',
'Berkshire Hathaway Specialty',
'BOWRING MARSH (BERMUDA) LTD.',
'Catlin',
'CERTA INSURANCE PARTNERS LTD',
'CHARTERAMA B.V.',
'Chaucer Insurance Company DAC',
'Chubb European Group SE',
'Chubb Versich.(Schweiz) AG',
'CNA Insurance Company Ltd.',
'Codan Forsikrings AS',
'Coface,Niederlassung in DE',
'COGITANDA INSURANCE SERVICE',
'Colonnade Insurance S.A.',
'Concordia Vers. Ges. a.G.',
'Concordia Versicherungs-Ges.',
'Condor Allgemeine Versiche-',
'Condor Allgemeine Versicherungs',
'Continentale Lebensversiche-',
'Convex Europe S.A.',
'Convex Insurance UK Limited',
'COOPER GAY S.A.',
'Corvus Underwriting GmbH',
'CREBITA GMBH',
'Credendo-Short-Term Non-EU',
'D.A.S. Deutscher Automobil -',
'DB Insurance Co.Limited',
'Delvag Versicherungs-AG',
'Deurag Deutsche Rechtsschutz-',
'DEVK Deutsche Eisenbahn Vers.',
'Dialog Versicherung AG',
'Dialog Versicherungs-AG',
'Die Haftpflichtkasse VVaG',
'DROEGE & SOHN*G. A.',
'DUAL DEUTSCHL. GMBH',
'DUAL EUROPE GMBH',
'DUAL UNDERWRITING IRELAND DAC',
'DUMMY CARRIER',
'EF MARINE PTE LTD',
'Eni Insurance Ltd.',
'ERGO Lebensversicherung AG',
'ERGO Versicherung AG',
'ERGO Versicherung AG; vorm.',
'ERGO_VI',
'EUCLID TRANSACTIONAL EUROPE',
'Euler Hermes',
'EUROPA Krankenversicherung',
'EUROSHIP ASSEK.GMBH&CO.KG',
'Everest Insurance (Ireland)DAC',
'EXTREMUS Versicherungs AG',
'Falcon Insurance Company',
'FIDELIS INSURANCE IRELAND DAC',
'FINLEX GMBH',
'First Capital Insurance Ltd.',
'FM Insurance Company Ltd.',
'FM Insurance Europe SA',
'GAEDE & GLAUERDT',
'Gard Marine & Energy Insurance',
'Gard Marine & Energy Ltd.',
'GARD P&I (Bermuda) Ltd.',
'Gartenbau-Versicherung VVaG',
'Generali Lebensvers. AG',
'Generali Seguros S.A',
'Generali T.U.S.A.',
'Generali Versicherung AG',
'GEO UNDERWRITING EUROPE B.V.',
'GERDITEX GMBH & CO. KG',
'Global Aerospace Underwriting',
'Globality S.A.',
'GLOE VERS.',
'Gothaer Allgemeine Ver-',
'Gothaer Allgemeine Vers.-AG',
'Gothaer Lebensversicherung AG',
'GRAUERHOLZ GMBH*HANS L.',
'Great American Insurance',
'Great Lakes Insurance SE',
'GUY CARPENTER & COMPANY GMBH',
'GVO Versicherung',
'Hallesche Kranken-',
'Hamburger Feuerkasse Versiche-',
'Hanse-Merkur Krankenversiche-',
'HCC International Insurance',
'HDI- Gerling Lebensvers. AG',
'HDI Global SE',
'HDI Global SE - Ireland',
'HDI Global SE (Rechtsschutz)',
'HDI Global Specialty SE',
'HDI Hannover Versicherung AG',
'HDI Lebensversicherung AG',
'HDI Versicherung AG',
'HDI Versicherung AG Magyarországi',
'Helvetia Global Solutions AG',
'Helvetia Schweizerische',
'Helvetia Versicherungs-AG',
'HERMANN FIRGAU ASSECURADEUR',
'Hiscox S.A.',
'HKVA GMBH',
'HOMANN VERSICHERUNGS-AG. GMBH',
'HPA HAMB. PHöNIX ASSEK. GMBH',
'ICEN Risk BV',
'IDUNA Vereinigte Lebensver-',
'IF P&C Insurance Co. Ltd.',
'if Schadenversicherung AG',
'ILSENBURGER GROBBLECH GMBH',
'India International Ins.Pte.Lt',
'INTER Allgemeine Versicherung',
'INTERRISK',
'Interrisk Versicherungs-AG',
'IRONSHORE AGENCY LTD.',
'ITAS Mutua-Gruppo ITAS Assigur',
'Itzehoer Versicherung',
'KA KöLN.ASSEKURANZ',
'KRAVAG-LOGISTIC Versicherungs-',
'Kravag-Sach Vers. d. Deutsch.',
'KROSE GMBH & CO. KG',
'LAMPE & SCHWARTZE',
'Lancashire Insurance',
'Landschaftliche Brandkasse',
'LEUE & NILL',
'LIBERTY MANAGING AGENCY LTD',
'Liberty Mutual Insurance',
'LIBERTY SPECIALTY MARKETS',
'Lloyds',
'Lloyds Insurance Company S.A.',
'LVM Landwirtschaftlicher Ver-',
'Mannheimer Versicherung',
'MARINE BENEFITS AS',
'Markel Insurance SE',
'Markel International Insurance',
'MARKEL SYNDICATE MGMT. LIMITED',
'MARSH (SINGAPORE) PTE LTD',
'MARSH B.V.',
'MARSH IRELAND BROKERS LTD UK',
'MARSH LTD UK IBA RETAIL',
'MARSH LTD.',
'MARSH NV/SA (UK BRANCH)'
'MARSH NV/SA UK BRANCH (B)'
'MARSH S.A.'
'MARSH S.P.A.'
'Medien-Versicherung a.G.'
'Mitsui Sumitomo Insurance'
'Mosaic Insurance Services Europe GmbH'
'MS Amlin Insurance SE'
'MS AMLIN MARINE N.V.'
'MSIG Insurance Europe AG'
'Münchener Rückversicherungs-',
'MUND & FESTER',
'Mund & Fester GmbH',
'MX Underwriting Europe',
'Newline Europe Versicherung AG',
'Newline Insurance Company Ltd.',
'NHA HAMBURGER ASSEKURANZ-',
'Norwegian Hull Club',
'Nürnberger Allgemeine Ver-',
'Öffentliche Sachversicherung',
'Oldenburgische Landesbrand-',
'ÖRAG Rechtsschutzversiche-',
'ÖSA öffentliche Feuerversich-',
'PANTAENIUS GMBH & CO. KG',
'PartnerRE Ireland Insur. dac',
'Pohjola Insurance Ltd.',
'POST & CO',
'PRO MGA SOLUTIONS EUROPE GMBH',
'PROBITAS SYNDICATE 1492',
'Provinzial Nord',
'Provinzial Versicherung AG',
'Pseudo VR Beteiligung offen',
'Pseudo-VR für Honorare',
'QBE Europe SA/NV',
'QBE Insurance (Europe)Limited',
'R+V Allgemeine Versicherung AG',
'RAUCHHAUPT & SENFTLEBEN*V.',
'RheinLand Versicherungs-',
'RISKPOINT A/S DIR. F. DEUTSCHL',
'RISKPOINT A/S DIR.F. DEUTSCHL.',
'RISKPOINT AB (SWEDEN)',
'RISKPOINT AS',
'Roland Rechtsschutz-Vers.',
'RSA Luxembourg S.A.',
'Ryan Specialty Nordics AB,Spanish Branch',
'Saarland Feuerversicherung AG',
'SCHRöTER GMBH*CARL',
'Schweizerische Mobiliar Vers.',
'SCOR',
'Scor Europe SE',
'SCOR UK Company Ltd.',
'SHB Allgemeine Versicherung',
'Shipowners Mutual Protection',
'SI Insurance (Europe) SA',
'SIGNAL IDUNA Krankenver.-',
'Signal-Iduna',
'Societa Cattolica di',
'Sopockie Towarzystwo',
'Sparkassen-Vers. Sachsen',
'SRC SPECIAL RISK CONSOR. GMBH',
'Starr Europe Insurance Limited',
'Starr International (Europe)',
'SV Sparkassen-Versicherung',
'Swiss Re Germany AG',
'Swiss RE International SE',
'The Standard Club Ireland DAC',
'The Swedish Club',
'THOMAS MILLER SPECIALTY GMBH',
'TLI CERTA EUROPE GMBH - UK Branch',
'Tokio Marine Europe S.A.',
'Tokio Marine Europe SA.',
'Towarzystwo Ubezpieczen i Reasekuracji',
'TRANSACT RISK PARTNERS',
'Travelers Insurance Comp. Ltd',
'UK P&I Club N.V.',
'UNIQA Insurance',
'UNIQA Österreich',
'Universitätsklinik Düsseld.AöR',
'VALE INSUR.PARTNERS EUROPE B.V'
'Versicherungskammer Bayern'
'Versicherungsstelle f.d. Wirt-',
'VHV Allgemeine Versicherung AG',
'VHV Vereinigte Hannoversche',
'VICTOR DEUTSCHLAND GMBH',
'VIENNA INSURANCE GROUP AG',
'VON LAUFF UND BOLZ',
'VOV GMBH',
'Vr nur Zie Vermittler',
'W. Droege Assekuradeur GmbH',
'W.R. Berkley Europe AG',
'W.R. Berkley Insurance',
'Waldenburger Versicherung AG',
'Westfälische Provinz.-Lebens-',
'WGV-Versicherung AG',
'White Rock Insurance (Europe)',
'Wiener Städtische Vers. AG',
'Württ. Gemeinde-Versicherung',
'Württembergische',
'Württembergische Versicherung',
'XL CATLIN SERVICES SE',
'XL Insurance Company Ltd.',
'XL Insurance Company SE',
'XL Insurance Company SE (Dublin Branch)',
'XL Insurance Company SE AXA Co',
'Zavarovalnica Triglav, d.d.',
'Zurich Ins. plc,Niederl. für',
'Zurich Insurance Company',
'Zurich Insurance plc',
'Zurich Insurance plc Rechts-',
'Zurich Insurance plc.',
'Zurich Lebensversicherungs-AG',
'Zürich Versicherungs-',
'kein Versicherer gewählt']
#endregion
#region ***involved_insurer_opt***
involved_insurer_opt = ['nicht zutreffend', 'ACQUINEX GMBH',
'AIG Europe S.A.',
'AIG Europe SA',
'AIG Europe SA (Denmark Branch)',
'Aioi Nissay Dowa Insurance',
'Allcura Versicherungs-AG',
'Allianz Elementar Vers.-AG',
'ALLIANZ ESA GMBH',
'Allianz Global Corporate &',
'Allianz Lebensversicherungs-AG',
'Allianz Versicherung AG',
'Allianz Versicherung AG,',
'Allianz Versicherungs-',
'Allianz Versicherungs-AG',
'Allied World Assurance Company',
'ALTA SIGNA EUROPE BV',
'Alte Leipziger Vers. AG',
'ALTE LEIPZIGER Versicherung',
'AMBRIDGE EUROPE GMBH & CO. KG',
'American Intern.Group UK Ltd.',
'AMERICAN INTERNATIONAL UNDER-',
'ANV SPECIALTY EUROPE S.L.',
'APPLIED FINANCIAL LINESINT.SAS',
'ARAG SE',
'ASSEKURANZ-KONTOR MONTAN GMBH',
'ASSEKURANZ-UNION',
'Assicurazioni Generali S.p.A',
'ASSPRO MANAGERLINE AG',
'Assuranceforeningen Gard',
'AT NORDDEUT. ASSEKURADEUR GMBH',
'Atradius Kreditversicherung',
'Auxilia Allg. Rechtsschutz-',
'AWP Health & Life SA',
'AXA Krankenversicherung AG',
'AXA Versicherung AG',
'Axis Specialty Europe SE',
'BA die Bayerische Allgemeine',
'Badischer Gemeinde-Ver-',
'Baloise Sachversicherung AG',
'BARKMANN*FRIEDRICH',
'Barmenia Krankenversicherung',
'Basler Versicherungs-',
'Bayer. Versicherungsverband',
'Bayerische Landesbrandver-',
'BDJ ASSEKURADEUR GMBH',
'Beazley Insurance dac',
'BEAZLEY INSURANCE DAC MüNCHEN',
'Berkshire Hathaway European',
'Berkshire Hathaway Specialty',
'BOWRING MARSH (BERMUDA) LTD.',
'Catlin',
'CERTA INSURANCE PARTNERS LTD',
'CHARTERAMA B.V.',
'Chaucer Insurance Company DAC',
'Chubb European Group SE',
'Chubb Versich.(Schweiz) AG',
'CNA Insurance Company Ltd.',
'Codan Forsikrings AS',
'Coface,Niederlassung in DE',
'COGITANDA INSURANCE SERVICE',
'Colonnade Insurance S.A.',
'Concordia Vers. Ges. a.G.',
'Concordia Versicherungs-Ges.',
'Condor Allgemeine Versiche-',
'Condor Allgemeine Versicherungs',
'Continentale Lebensversiche-',
'Convex Europe S.A.',
'Convex Insurance UK Limited',
'COOPER GAY S.A.',
'Corvus Underwriting GmbH',
'CREBITA GMBH',
'Credendo-Short-Term Non-EU',
'D.A.S. Deutscher Automobil -',
'DB Insurance Co.Limited',
'Delvag Versicherungs-AG',
'Deurag Deutsche Rechtsschutz-',
'DEVK Deutsche Eisenbahn Vers.',
'Dialog Versicherung AG',
'Dialog Versicherungs-AG',
'Die Haftpflichtkasse VVaG',
'DROEGE & SOHN*G. A.',
'DUAL DEUTSCHL. GMBH',
'DUAL EUROPE GMBH',
'DUAL UNDERWRITING IRELAND DAC',
'DUMMY CARRIER',
'EF MARINE PTE LTD',
'Eni Insurance Ltd.',
'ERGO Lebensversicherung AG',
'ERGO Versicherung AG',
'ERGO Versicherung AG; vorm.',
'ERGO_VI',
'EUCLID TRANSACTIONAL EUROPE',
'Euler Hermes',
'EUROPA Krankenversicherung',
'EUROSHIP ASSEK.GMBH&CO.KG',
'Everest Insurance (Ireland)DAC',
'EXTREMUS Versicherungs AG',
'Falcon Insurance Company',
'FIDELIS INSURANCE IRELAND DAC',
'FINLEX GMBH',
'First Capital Insurance Ltd.',
'FM Insurance Company Ltd.',
'FM Insurance Europe SA',
'GAEDE & GLAUERDT',
'Gard Marine & Energy Insurance',
'Gard Marine & Energy Ltd.',
'GARD P&I (Bermuda) Ltd.',
'Gartenbau-Versicherung VVaG',
'Generali Lebensvers. AG',
'Generali Seguros S.A',
'Generali T.U.S.A.',
'Generali Versicherung AG',
'GEO UNDERWRITING EUROPE B.V.',
'GERDITEX GMBH & CO. KG',
'Global Aerospace Underwriting',
'Globality S.A.',
'GLOE VERS.',
'Gothaer Allgemeine Ver-',
'Gothaer Allgemeine Vers.-AG',
'Gothaer Lebensversicherung AG',
'GRAUERHOLZ GMBH*HANS L.',
'Great American Insurance',
'Great Lakes Insurance SE',
'GUY CARPENTER & COMPANY GMBH',
'GVO Versicherung',
'Hallesche Kranken-',
'Hamburger Feuerkasse Versiche-',
'Hanse-Merkur Krankenversiche-',
'HCC International Insurance',
'HDI- Gerling Lebensvers. AG',
'HDI Global SE',
'HDI Global SE - Ireland',
'HDI Global SE (Rechtsschutz)',
'HDI Global Specialty SE',
'HDI Hannover Versicherung AG',
'HDI Lebensversicherung AG',
'HDI Versicherung AG',
'HDI Versicherung AG Magyarországi',
'Helvetia Global Solutions AG',
'Helvetia Schweizerische',
'Helvetia Versicherungs-AG',
'HERMANN FIRGAU ASSECURADEUR',
'Hiscox S.A.',
'HKVA GMBH',
'HOMANN VERSICHERUNGS-AG. GMBH',
'HPA HAMB. PHöNIX ASSEK. GMBH',
'ICEN Risk BV',
'IDUNA Vereinigte Lebensver-',
'IF P&C Insurance Co. Ltd.',
'if Schadenversicherung AG',
'ILSENBURGER GROBBLECH GMBH',
'India International Ins.Pte.Lt',
'INTER Allgemeine Versicherung',
'INTERRISK',
'Interrisk Versicherungs-AG',
'IRONSHORE AGENCY LTD.',
'ITAS Mutua-Gruppo ITAS Assigur',
'Itzehoer Versicherung',
'KA KöLN.ASSEKURANZ',
'KRAVAG-LOGISTIC Versicherungs-',
'Kravag-Sach Vers. d. Deutsch.',
'KROSE GMBH & CO. KG',
'LAMPE & SCHWARTZE',
'Lancashire Insurance',
'Landschaftliche Brandkasse',
'LEUE & NILL',
'LIBERTY MANAGING AGENCY LTD',
'Liberty Mutual Insurance',
'LIBERTY SPECIALTY MARKETS',
'Lloyds',
'Lloyds Insurance Company S.A.',
'LVM Landwirtschaftlicher Ver-',
'Mannheimer Versicherung',
'MARINE BENEFITS AS',
'Markel Insurance SE',
'Markel International Insurance',
'MARKEL SYNDICATE MGMT. LIMITED',
'MARSH (SINGAPORE) PTE LTD',
'MARSH B.V.',
'MARSH IRELAND BROKERS LTD UK',
'MARSH LTD UK IBA RETAIL',
'MARSH LTD.',
'MARSH NV/SA (UK BRANCH)'
'MARSH NV/SA UK BRANCH (B)'
'MARSH S.A.'
'MARSH S.P.A.'
'Medien-Versicherung a.G.'
'Mitsui Sumitomo Insurance'
'Mosaic Insurance Services Europe GmbH'
'MS Amlin Insurance SE'
'MS AMLIN MARINE N.V.'
'MSIG Insurance Europe AG'
'Münchener Rückversicherungs-',
'MUND & FESTER',
'Mund & Fester GmbH',
'MX Underwriting Europe',
'Newline Europe Versicherung AG',
'Newline Insurance Company Ltd.',
'NHA HAMBURGER ASSEKURANZ-',
'Norwegian Hull Club',
'Nürnberger Allgemeine Ver-',
'Öffentliche Sachversicherung',
'Oldenburgische Landesbrand-',
'ÖRAG Rechtsschutzversiche-',
'ÖSA öffentliche Feuerversich-',
'PANTAENIUS GMBH & CO. KG',
'PartnerRE Ireland Insur. dac',
'Pohjola Insurance Ltd.',
'POST & CO',
'PRO MGA SOLUTIONS EUROPE GMBH',
'PROBITAS SYNDICATE 1492',
'Provinzial Nord',
'Provinzial Versicherung AG',
'Pseudo VR Beteiligung offen',
'Pseudo-VR für Honorare',
'QBE Europe SA/NV',
'QBE Insurance (Europe)Limited',
'R+V Allgemeine Versicherung AG',
'RAUCHHAUPT & SENFTLEBEN*V.',
'RheinLand Versicherungs-',
'RISKPOINT A/S DIR. F. DEUTSCHL',
'RISKPOINT A/S DIR.F. DEUTSCHL.',
'RISKPOINT AB (SWEDEN)',
'RISKPOINT AS',
'Roland Rechtsschutz-Vers.',
'RSA Luxembourg S.A.',
'Ryan Specialty Nordics AB,Spanish Branch',
'Saarland Feuerversicherung AG',
'SCHRöTER GMBH*CARL',
'Schweizerische Mobiliar Vers.',
'SCOR',
'Scor Europe SE',
'SCOR UK Company Ltd.',
'SHB Allgemeine Versicherung',
'Shipowners Mutual Protection',
'SI Insurance (Europe) SA',
'SIGNAL IDUNA Krankenver.-',
'Signal-Iduna',
'Societa Cattolica di',
'Sopockie Towarzystwo',
'Sparkassen-Vers. Sachsen',
'SRC SPECIAL RISK CONSOR. GMBH',
'Starr Europe Insurance Limited',
'Starr International (Europe)',
'SV Sparkassen-Versicherung',
'Swiss Re Germany AG',
'Swiss RE International SE',
'The Standard Club Ireland DAC',
'The Swedish Club',
'THOMAS MILLER SPECIALTY GMBH',
'TLI CERTA EUROPE GMBH - UK Branch',
'Tokio Marine Europe S.A.',
'Tokio Marine Europe SA.',
'Towarzystwo Ubezpieczen i Reasekuracji',
'TRANSACT RISK PARTNERS',
'Travelers Insurance Comp. Ltd',
'UK P&I Club N.V.',
'UNIQA Insurance',
'UNIQA Österreich',
'Universitätsklinik Düsseld.AöR',
'VALE INSUR.PARTNERS EUROPE B.V'
'Versicherungskammer Bayern'
'Versicherungsstelle f.d. Wirt-',
'VHV Allgemeine Versicherung AG',
'VHV Vereinigte Hannoversche',
'VICTOR DEUTSCHLAND GMBH',
'VIENNA INSURANCE GROUP AG',
'VON LAUFF UND BOLZ',
'VOV GMBH',
'Vr nur Zie Vermittler',
'W. Droege Assekuradeur GmbH',
'W.R. Berkley Europe AG',
'W.R. Berkley Insurance',
'Waldenburger Versicherung AG',
'Westfälische Provinz.-Lebens-',
'WGV-Versicherung AG',
'White Rock Insurance (Europe)',
'Wiener Städtische Vers. AG',
'Württ. Gemeinde-Versicherung',
'Württembergische',
'Württembergische Versicherung',
'XL CATLIN SERVICES SE',
'XL Insurance Company Ltd.',
'XL Insurance Company SE',
'XL Insurance Company SE (Dublin Branch)',
'XL Insurance Company SE AXA Co',
'Zavarovalnica Triglav, d.d.',
'Zurich Ins. plc,Niederl. für',
'Zurich Insurance Company',
'Zurich Insurance plc',
'Zurich Insurance plc Rechts-',
'Zurich Insurance plc.',
'Zurich Lebensversicherungs-AG',
'Zürich Versicherungs-',
'kein Versicherer gewählt']
#endregion
#region ***wording_opt***
wording_opt =[ '1 – SEP (01/2014) GOLD',
'2 – SEP (01/2014) PLATIN',
'3 – SEP (01/08)',
'4 – Allgefahrenversicherung für Bürobetriebe (05/2015)',
'5 – Allgefahrenversicherung für Bürobetriebe (01/08)',
'6 – FM Global Advantage (FMGA)',
'7 – AFM proVisio',
'IHV 2011',
'IHV 2015',
'IHV 2016',
'IHV 2018',
'Marsh Cargo 2012 inklusive Cyber-/Pandemieklausel (Grundfassung)',
'Marsh Cargo 2022 inklusive Cyber-/Pandemieklausel (Grundfassung)',
'Mustervereinbarungen mit Versicherern Basis Marsh Cargo 2022',
'Marsh-Bedingungen für die Maschinenversicherung (02/2016, stand: 12/2015)',
'Marsh-Bedingungen für die Maschinenversicherung (11/2011, stand: 10/2008)',
'Marsh-Bedingungen für die Maschinenversicherung (12/2015, stand: 12/2015)',
'Marsh-Bedingungen für die Maschinenversicherung (11/2011_2, stand: 10/2008)',
'Marsh-Bedingungen für die Maschinenversicherung (10/2014, stand: 10/2008)',
'Marsh-Bedingungen für die Maschinen- und Kaskoversicherung (12/2015, stand: 12/2008)',
'Marsh-Bedingungen für die Maschinen- und Kaskoversicherung (11/2011, stand: 10/2008)',
'Marsh-Bedingungen für die Maschinen- und Kaskoversicherung (10/2014, stand: 10/2008)',
'Marsh-Bedingungen für die Maschinen- und Kaskoversicherung (02/2016, stand: 12/2015)',
'Marsh-Bedingungen für die Bauleistungsversicherung (07/2017, stand: 04/2016)',
'Marsh Bedingungen zur Montageversicherung (04/2018, stand: 04/2016)',
'Marsh Bedingungen zur Montageversicherung (10/2014, stand: 10/2008)',
'Marsh Bedingungen zur Montageversicherung (08/2018_2, stand: 08/2018)',
'Marsh-Bedingungen Elektronikversicherung MEL 2018 (07/2018_2, stand: 08/2018)',
'Marsh-Bedingungen Elektronikversicherung MEL 2018 (10/2016, stand: 10/2014)',
'Marsh-Zusatzbedingungen Photovoltaik zu den MEL 2014 (04/2015, stand: 10/2014)',
'Marsh-Bedingungen zur Allgefahrenversicherung Mplus (10/2014, stand: 10/2008)',
'Marsh-Bedingungen zur Allgefahrenversicherung Mplus (01/2020_2, stand: 10/2018)',
'Marsh-Bedingungen zur Versicherung von Energieerzeugungsanlagen (11/2011, stand: 05/2009)',
'Marsh-Bedingungen zur Versicherung von Energieerzeugungsanlagen (10/2014, stand: 05/2009)',
'Marsh-Zusatzbedingungen BU- und Mehrkostenschadenversicherung (12/2014, stand: 10/2010)',
'Marsh-Zusatzbedingungen BU- und Mehrkostenschadenversicherung (02/2012, stand: 02/2012)',
'Marsh-Zusatzbedingungen BU- und Mehrkostenschadenversicherung (12/2015, stand: 12/2015)',
'Vertrags Bedingungen Marsh-Windkraftanlagen (MMW 2016) M+MBU (02/2016, stand: 02/2016)',
'Marsh GUB 2016 (R+V Facility)',
'Marsh GUB 2014 (R+V Facility)',
'Marsh GUB 2011 (R+V Facility)',
'Marsh USRU 2017 (Roland Facility)', 
'Marsh USRU 2018 (Roland Facility)', 
'Marsh USRU 2020 (Roland Facility)', 
'Marsh-Bedingungen für die kombinierte Projektversicherung (stand: 09/2020)', 'kein Wording gewählt' ] 
#endregion
#region ***platz_opt***
platz_opt = ['schwieriges Placement',
 'leichtes Placement',
 'normales Placement',
 'keine Platzierung gewählt']
#endregion
#region ***risiko_opt***
risiko_opt = ['schweres Risiko ',
 'leichtes Risiko',
 'mittleres Risiko',
 'keine Risikoart gewählt']
#endregion
#region ***ja_nein_opt***
ja_nein_opt =['ja', 'nein', 'keine Auswahl getroffen']
#endregion
#region ***vertragsart_opt***
vertragsart_opt = ['Primary',
'1. Layer',
'2. Layer',
'3. Layer',
'4. Layer',
'5. Layer',
'6. Layer',
'7. Layer',
'8. Layer',
'9. Layer',
'10. Layer',
'Primary - Abrechnungsvertrag (vertikale Platzierung)',
'1. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'2. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'3. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'4. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'5. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'6. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'7. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'8. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'9. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'10. Layer - Abrechnungsvertrag (vertikale Platzierung)',
'keine Vertragsart gewählt']
#endregion
#region ***ausschreibung_opt***
ausschreibung_opt = ['Ausschreibung (Marktbefragung)',
'Ausschreibung (zielgerichtet)',
'Ausschreibung (Beteiligung)',
'keine Ausschreibung', 'keine Auswahl getroffen']
#endregion
#region ***status_opt***
status_opt = ['verlängert - Angebot angenommen',
'verlängert - tacit Renewal',
'offen - Angebot liegt beim Kunden vor',
'offen - Angebot liegt dem Kunden nicht vor',
'offen - Angebot liegt beim Kunden in Teilen vor',
'offen'] # offen ist der Standardstatus
#endregion
#region ***renewal_opt***
renewal_opt = ['unverändertes Konsortium', 
'Wechsel führender Versicherer',
'Wechsel beteiligter Versicherer', 
'keine Auswahl getroffen']
#endregion
#region ***schicksal_opt***
schicksal_opt = ['Mandat gehalten',
'Mandat verloren',
'Mandat neu', 
'keine Auswahl getroffen']
#endregion
#region ***ausschreibung_opt***
ausschreibung_opt = ['Kein Auswahl getroffen',
 'Aktiv',
'Gezeichnet',
'Vorgang abgebrochen', 
'VR hat abgelehnt', 
'keine Rückmeldung vom Versicherer', 
'Angebot des VR abgelehnt', 
'Quotiert']
#endregion
#region ***sql_columns***
sql_columns = [
'ivp',
'haupt_vertragsdeckungssumme',
'selbstbehalt_attachment_point',
'`hoehe_der_courtage_lokalpolicen(in_%)`',
'`akt._jahresprogrammbeitrag(inkl._lopos)`',
'vertragsart',
'vertical_pricing',
'risiko_dialog',
'risikoinfos',
'jahresfahrplan_vom_ce_erhalten',
'ausschreibung_fuer_kommendes_renewal',
'ausschreibung_an_versicherer_1',
'vr_2',
'vr_3',
'vr_4',
'vr_5',
'vr_6',
'vr_7',
'vr_8',
'vr_9',
'vr_10',
'vr_11',
'vr_12',
'vr_13',
'vr_14',
'vr_15',
'angebotene_praemie_1',
'angebotene_praemie_2',
'angebotene_praemie_3',
'angebotene_praemie_4',
'angebotene_praemie_5',
'angebotene_praemie_6',
'angebotene_praemie_7',
'angebotene_praemie_8',
'angebotene_praemie_9',
'angebotene_praemie_10',
'angebotene_praemie_11',
'angebotene_praemie_12',
'angebotene_praemie_13',
'angebotene_praemie_14',
'angebotene_praemie_15',
'status_des_angebots_1',
'status_des_angebots_2',
'status_des_angebots_3',
'status_des_angebots_4',
'status_des_angebots_5',
'status_des_angebots_6',
'status_des_angebots_7',
'status_des_angebots_8',
'status_des_angebots_9',
'status_des_angebots_10',
'status_des_angebots_11',
'status_des_angebots_12',
'status_des_angebots_13',
'status_des_angebots_14',
'status_des_angebots_15',
'platzierungsart',
'risikoart',
'kuefri',
'status',
'renewalergebnis',
'neuer_fuehrender_versicherer',
'`neue_beteiligte_versicherer(1)`',
'`neue_beteiligte_versicherer(2)`',
'`neue_beteiligte_versicherer(3)`',
'`neue_beteiligte_versicherer(4)`',
'`neue_beteiligte_versicherer(5)`',
'`fuehrungsquote(in_%)`',
'`beteiligungsquote(in_%)_1`',
'`beteiligungsquote(in_%)_2`',
'`beteiligungsquote(in_%)_3`',
'`beteiligungsquote(in_%)_4`',
'`beteiligungsquote(in_%)_5`',
'`neuer_jahresprogrammbeitrag(100%_exkl.lopos)`',
'`neuer_jahresprogrammbeitrag(100%_inkl.lopos)`',
'pdcs',
'`allokation+rechnung`',
'mgc',
'pol',
'schicksal_des_kunden',
'wording_version',
'bemerkung'
]
#endregion