import sqlite3

# Verbindung zur SQLite-Datenbank herstellen. Diese Anweisung erstellt die Datei, falls sie noch nicht existiert.
conn = sqlite3.connect('manuelle_daten.db')

# Erstellen eines Cursor-Objekts mittels der Verbindung
cursor = conn.cursor()

# SQL-Befehl zum Erstellen der Tabelle
cursor.execute('''
CREATE TABLE IF NOT EXISTS manuelle_daten (
vertragsnummer INTEGER PRIMARY KEY,
ivp TEXT,
haupt_vertragsdeckungssumme REAL,
selbstbehalt_attachment_point REAL,
`hoehe_der_courtage_lokalpolicen(in_%)` REAL,
`akt._jahresprogrammbeitrag(inkl._lopos)` REAL,
vertragsart TEXT,
vertical_pricing TEXT,
risiko_dialog TEXT,
risikoinfos TEXT,
jahresfahrplan_vom_ce_erhalten TEXT,
ausschreibung_fuer_kommendes_renewal TEXT,
ausschreibung_an_versicherer_1 TEXT,
vr_2 TEXT,
vr_3 TEXT,
vr_4 TEXT,
vr_5 TEXT,
vr_6 TEXT,
vr_7 TEXT,
vr_8 TEXT,
vr_9 TEXT,
vr_10 TEXT,
vr_11 TEXT,
vr_12 TEXT,
vr_13 TEXT,
vr_14 TEXT,
vr_15 TEXT,
angebotene_praemie_1 REAL,
angebotene_praemie_2 REAL,
angebotene_praemie_3 REAL,
angebotene_praemie_4 REAL,
angebotene_praemie_5 REAL,
angebotene_praemie_6 REAL,
angebotene_praemie_7 REAL,
angebotene_praemie_8 REAL,
angebotene_praemie_9 REAL,
angebotene_praemie_10 REAL,
angebotene_praemie_11 REAL,
angebotene_praemie_12 REAL,
angebotene_praemie_13 REAL,
angebotene_praemie_14 REAL,
angebotene_praemie_15 REAL,
status_des_angebots_1 TEXT,
status_des_angebots_2 TEXT,
status_des_angebots_3 TEXT,
status_des_angebots_4 TEXT,
status_des_angebots_5 TEXT,
status_des_angebots_6 TEXT,
status_des_angebots_7 TEXT,
status_des_angebots_8 TEXT,
status_des_angebots_9 TEXT,
status_des_angebots_10 TEXT,
status_des_angebots_11 TEXT,
status_des_angebots_12 TEXT,
status_des_angebots_13 TEXT,
status_des_angebots_14 TEXT,
status_des_angebots_15 TEXT,
platzierungsart TEXT,
risikoart TEXT,
kuefri TEXT,
status TEXT,
renewalergebnis TEXT,
neuer_fuehrender_versicherer TEXT,
`neue_beteiligte_versicherer(1)` TEXT,
`neue_beteiligte_versicherer(2)` TEXT,
`neue_beteiligte_versicherer(3)` TEXT,
`neue_beteiligte_versicherer(4)` TEXT,
`neue_beteiligte_versicherer(5)` TEXT,
`neue_beteiligte_versicherer(6)` TEXT,
`neue_beteiligte_versicherer(7)` TEXT,
`neue_beteiligte_versicherer(8)` TEXT,
`neue_beteiligte_versicherer(9)` TEXT,
`neue_beteiligte_versicherer(10)` TEXT,
`fuehrungsquote(in_%)` TEXT,
`beteiligungsquote(in_%)_1` TEXT,
`beteiligungsquote(in_%)_2` TEXT,
`beteiligungsquote(in_%)_3` TEXT,
`beteiligungsquote(in_%)_4` TEXT,
`beteiligungsquote(in_%)_5` TEXT,
`beteiligungsquote(in_%)_6` TEXT,
`beteiligungsquote(in_%)_7` TEXT,
`beteiligungsquote(in_%)_8` TEXT,
`beteiligungsquote(in_%)_9` TEXT,
`beteiligungsquote(in_%)_10` TEXT,
`neuer_jahresprogrammbeitrag(100%_exkl.lopos)` REAL,
`neuer_jahresprogrammbeitrag(100%_inkl.lopos)` REAL,
pdcs TEXT,
`allokation+rechnung` TEXT,
mgc TEXT,
pol TEXT,
schicksal_des_kunden TEXT,
wording_version TEXT,
bemerkung TEXT
);
''')
# Änderungen an der Datenbank bestätigen
conn.commit()

# Verbindung zur Datenbank schließen
conn.close()